config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: "Task was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.expect(task: [ :title, :description, :complete ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <% if notice %>
    <div id="liveToast" class="toast align-items-center text-bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body">
            <%= notice %>
        </div>
    </div>
    <% end %>
</div>

<script>
    document.addEventListener("turbo:load", () => {
        const toastel = document.getElementById('liveToast');
        if (toastel) {
            const toast = new bootstrap.Toast(toastel);
            toast.show();
        }
    });
</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid mx-5">
        <%= image_tag "logo.png", style: "width: 30px; height: 30px" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Task list</a>
                </li>
                <li class="nav-item">
                    <%= link_to "New task", new_task_path, class: "nav-link" %>
                </li>

            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Todoapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= favicon_link_tag "logo.png"%>
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
</head>

<body>
    <%= render "layouts/navbar"%>
    <%= yield %>
    <%= render "layouts/footer"%>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>

</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
<% if task.errors.any? %>
<div style="color: red">
    <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

    <ul>
        <% task.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div>
    <%= form.label :title, class: "form-check-label" %>
    <%= form.text_field :title, class: "form-control" %>
</div>

<div>
    <%= form.label :description, class: "form-check-label" %>
    <%= form.textarea :description, class: "form-control" %>
</div>

<div class="d-flex justify-content-between">
    <%= form.label :complete, class: "form-check-label" %>
    <%= form.checkbox :complete, class: "form-check-input" %>
</div>

<div class="text-center">
    <%= form.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/tasks/_task.html.erb
<div class="d-flex justify-content-center mx-5 ">
    <div id="<%= dom_id task %>">
        <h2>
            <%= task.title %>
        </h2>


        <i>

            <%= task.description %>
            </p>
        </i>
        <p>
            <strong>Complete:</strong>
            <%= check_box_tag "task_complete", "true", task.complete, disabled: true %>

        </p>

    </div>
</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing task" %>

<h1 class="text-center">Editing task</h1>


<div class="d-flex justify-content-center">
    <%= render "form", task: @task %>

</div>

app/views/tasks/index.html.erb
<% content_for :title, "Task list" %>

<div class="d-flex flex-row justify-content-between mx-5">
    <h1 class="text-center">Task list</h1>
    <%= button_to "New task", new_task_path, method: :get,class: "btn btn-success" %>
</div>

<div id="tasks" class="mx-5">

    <% @tasks.each do |task| %>
    <div class="border border-2 rounded d-flex flex-row justify-content-between p-2 mb-2">
        <%= render task %>
        <div class="d-flex flex-column me-5">
            <%= button_to "Show this task", task, method: :get, class: "btn btn-primary mt-2", form: {class: "d-inline"}, style: "min-width: 133px" %>
            <%= button_to "Edit this task", edit_task_path(task),  method: :get, class: "btn btn-warning mt-2", form: {class: "d-inline"}, style: "min-width: 133px" %>
            <%= button_to "Delete this task", task, method: :delete, class: "btn btn-danger mt-2 ", form: {class: "d-inline"} , style: "min-width: 133px"%>
        </div>
    </div>
    <% end %>
</div>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>

<h1 class="text-center">New task</h1>

<div class="d-flex justify-content-center">
    <%= render "form", task: @task %>
</div>

app/views/tasks/show.html.erb
<% content_for :title, @task.title  %>
<%= render @task %>

<div class="d-flex flex-row justify-content-center gap-2">
    <%= button_to "Back to tasks", tasks_path, class: "btn btn-primary", method: :get %>
    <%= button_to "Edit this task", edit_task_path(@task), method: :get, class: "btn btn-warning"%>

    <%= button_to "Destroy this task", @task, method: :delete, class: "btn btn-danger"%>
</div>